### ISSUE TITLE
How to modify code to add .doc file type support?

### ISSUE THREAD

**Issue by stevevaius2015** [OpsConfig/OpenAI_Lab#2]
Is there any way to modify code for accepting MS Word type files? docx, doc etc...

**Comment by OpsConfig** [comment]
Hey @stevevaius2015,

I hadn't tried this process with docx before, but I did a quick test.

I think the easiest way would be to first convert your docx files to txt. And then some slight modifications to my code from the video.

To do the txt conversions I used: https://pypi.org/project/pypandoc/

I used the binary install so I didn't need to install pandoc separately since this is just a Python wrapper on the existing pandoc project.

```
pip install pypandoc_binary
```

For the script below you point it to a top level directory and it will find all the docx files in that directory as well as any lower level directories and it creates a copy of each file that is converted to .txt.

```python
import pypandoc
import os
import time
import sys

start_time=time.time()
path ='c:\\test' 

for root, directories, files in os.walk(path , topdown=False):
    for file in files:
        if file.lower().endswith(".docx"):
            name =(os.path.join(root,file))
            pypandoc.convert_file(name, 'plain', outputfile=name[:-5] +".txt")

end_time = time.time()
duration = end_time - start_time

print ("Cell Run Time: ", duration)
```

My test folder just had two identical docx files I created in two different directories just to make sure that it wouldn't just check the top level directory:

![image](https://user-images.githubusercontent.com/13853953/218284847-7c3307f2-9193-4bef-895c-6f9743751106.png)

![image](https://user-images.githubusercontent.com/13853953/218284795-4aade38d-e482-4dcf-9d14-be2377beeedb.png)

![image](https://user-images.githubusercontent.com/13853953/218284812-07160eeb-eb8c-42bf-8f0a-60ee121bfdcd.png)

If I run the script above I then get the following:

![image](https://user-images.githubusercontent.com/13853953/218284881-bb8fb534-493e-49f5-8a3e-95084a052813.png)

![image](https://user-images.githubusercontent.com/13853953/218284892-e938240b-94c8-43cf-b57f-b888fcc9916b.png)

Then I can run a slightly new version of my first script from the video that is modified to work on txt files instead of markdown without my metadata filtering code:

```python
import os
import time
import pandas as pd
import openai
import re
import requests
import sys
from num2words import num2words
import numpy as np
from openai.embeddings_utils import get_embedding, cosine_similarity
import tiktoken

openai.api_key = os.getenv("OPENAI_API_KEY") 
openai.organization = os.getenv("OPENAI_ORGANIZATION") 

start_time=time.time()
path ='c:\\test' #example: 'c:\\openai\\test'

d = []
text=""

for root, directories, files in os.walk(path , topdown=False):
    for file in files:
        if file.lower().endswith(".txt"):
            name =(os.path.join(root,file))
            f = open(name, "r",encoding="utf-8")
            for line in f:
                text +=line
            f.close()
            d.append({'FILE NAME': file ,'CONTENT': text})
            pd.DataFrame(d)
            metadata_counter = 0
            text=""
end_time = time.time()
duration = end_time - start_time
```

And then you can pick up on the next step in the original script and everything will work as in my video:

```
df = pd.DataFrame(d)
df
```

![image](https://user-images.githubusercontent.com/13853953/218285001-ce713ea4-3ddf-4d13-930f-0ee38885af17.png)

Hopefully this helps, thanks for the great question. I will probably put together a quick video on this, but I didn't want to make you wait. 

Cheers,

OpsConfig

**Comment by OpsConfig** [comment]
Full Jupyter notebook of the example described above is here: 
https://github.com/OpsConfig/OpenAI_Lab/blob/main/Embeddings-docx.ipynb

I will say the conversion library seems to be a little fragile. It wasn't handling certain really long file names, and I saw some random errors so I am not sure how suitable it will be for all use cases. But for a simple example of how to address your question it should at least give you a starting point.

Video answering your question is here:
https://youtu.be/H9nXtUkGL-U

Thanks for watching, and for the question.
