### ISSUE TITLE
multi-turn conversation issue

### ISSUE THREAD

**Issue by EricJoung1997** [OpsConfig/OpenAI_Lab#6]
I am very excited to use the code and thank you for your contribution!
I seem encountered an issue when running `ChatGPT_Demo_v2.ipynb`, when I input mildly long text (only nearby 1600 tokens, Chinese), it continuously returns "How may I assist you today? ", but the single-turn conversation is run truly when input same text. Here is my code:
```
# multi-turn conversation
openai.api_key = "XXX"
# openai.organization = os.getenv("OPENAI_ORGANIZATION") 

system_message = {"role": "system", "content": "You are a helpful assistant."}
max_response_tokens = 4000
token_limit= 4096
conversation=[]
conversation.append(system_message)

def num_tokens_from_messages(messages, model="gpt-3.5-turbo-0301"):
    encoding = tiktoken.encoding_for_model(model)
    num_tokens = 0
    for message in messages:
        num_tokens += 4  # every message follows <im_start>{role/name}\n{content}<im_end>\n
        for key, value in message.items():
            num_tokens += len(encoding.encode(value))
            if key == "name":  # if there's a name, the role is omitted
                num_tokens += -1  # role is always required and always 1 token
    num_tokens += 2  # every reply is primed with <im_start>assistant
    return num_tokens

while(True):
    user_input = input("Question：")     
    conversation.append({"role": "user", "content": user_input})
    conv_history_tokens = num_tokens_from_messages(conversation)

    while (conv_history_tokens+max_response_tokens >= token_limit):
        del conversation[1]
        conv_history_tokens = num_tokens_from_messages(conversation)
        
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages = conversation,
        # temperature=.7,
        max_tokens=max_response_tokens,
    )

    conversation.append({"role": "assistant", "content": response['choices'][0]['message']['content']})
    print("\nAnswer：" + response['choices'][0]['message']['content'] + "\n")

    if user_input == "ChatGPT STOP" :
      break
```

```
# single-turn conversation
def single_turn(mycontent):
  
  completion = openai.ChatCompletion.create(
      model="gpt-3.5-turbo",
      messages=[
          {"role": "system", "content": "You are a helpful assistant."},
          # {"role": "user", "content": "Who won the world series in 2020?"},
          # {"role": "assistant", "content": "The Los Angeles Dodgers won the World Series in 2020."},
          {"role": "user", "content": mycontent}
      ]
  )

  return completion.choices[0].message['content']
```

**Comment by OpsConfig** [comment]
@EricJoung1997 Hey, thanks for the question. Based on the description I think the issue you are facing is just that my code isn't doing any handling of scenarios where you have a large initial input on the first question + a very high max response tokens value that is close to the total token limit for the model.

So the issue is happening in this part of the code:     

```python
conv_history_tokens = num_tokens_from_messages(conversation)

    while (conv_history_tokens+max_response_tokens >= token_limit):
        del conversation[1]
```

So you send your first question with an input of approximately 1600 tokens this then results in the while loop being evaluated as:

```
while (1600 tokens + 4000 tokens >= 4096 tokens:
        del conversation[1] 
```

So what is happening is your 1600 token input is never getting sent to the model, it gets dropped and only the system message in index 0 is getting sent. Which is why it just keeps responding with a generic "How may I assist you today". So the quick fix/way to test if I am right, would be try setting `max_response_tokens = 250` rather than having it set to 4000.  

That should at least allow you to have a single turn of the conversation before things start getting deleted. (Keep in mind though with input sizes that large the model is going to quickly lose context of previous questions/answers.) If you swap to using GPT-4 with the 8K or 32 K models this would give you a little more clearance for longer conversation histories with large inputs to be preserved.

And certainly my code could be greatly improved to automatically handle cases like this in a more transparent way. I went for the simplest example possible, but unfortunately it's fairly easy to break my example code since it isn't doing any real edge case/error handling.

Cheers,

OpsConfig

**Comment by EricJoung1997** [comment]
Thank you for your response, it's working fine now.
